baseURL = "https://spencercadams.github.io/chipper"
languageCode = "en-us"
title = "Lindsey's Bakeshop"
theme = "hugo-serif-theme"
publishDir = "docs"

[params]
#google_analytics_id=""

[[menu.main]]
	name = "Tastings"
	url = "/tasting/"
    weight = 1

[[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 2

[[menu.main]]
	name = "Testimonials"
	url = "/testimonials/"
	weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
